worlds:
    playershops:
    - 6N6YMFEYB
    - KN6NBFP1A
    world:
    - QF9NILWCX
    - KP7NCBOYO
    - O6WG9I6VR
    - ML99DOURX
    - ZQMAB391L
    - O0OECXBVQ
    - MUJ8HQ40Z
    - DV2RFKK29
    - MUJ8HQ4HV
    - K99TORK84
    - 67B350L1Y
    - CIUG67POP
    - VP8LA6PPC
    - R4MCOE6JL
    - 01EIPEQSD
    - 0K7PGC1HW
    - CYQNQRTU6
    - CS54CB280
    - DQMGL1UND
    - PJG0A24F5
    - 6P9O4KX58
    - DCGDZEQSD
    - DFFFG2CVI
    - 50M3VQ58C
    - NS2L0PXFJ
    - O6WG9I6CN
    - 0L9RZVENG
    - DU2QBII8X
    - KWEF5ZGGI
    - 7HCYGA0UX
    - RHG0A39KO
    - 4V2BC89T0
    - 8DOK02UKJ
    - TDROX4VQM
    - R5EI7N5EM
    - K99TORKR7
    - HB3EVFDOR
    - ZCMKEIYZ5
    - W7ZTUWR6P
    - 4E0S0H8WE
    - KY2FF040J
    - ZQMAB39KO
    - JHYTYA4SQ
    - 22G8KREUE
    - DM18HM10K
    - VS83AFN1A
    - OXZNU1Y13
    - I39HW863K
    - FWRADS5NY
    - QF9NILWV1
    - CT7KVJQKS
    - C500TS162
    - DAKQ1ILF9
    - SF6BTT338
    - 7FFTMCWAJ
    - CIUG67P5M
    - T3XA6RNZK
    - HOUADUFXN
    - SOSHIO4LC
    - X382K1HKE
    - TW84M294F
    - ZSZU1ZXX7
    - ML99DOU8U
    - BAPDGAWW4
    - QCIFPLYCX
    - G64S83W0T
    - XJFLBABYJ
    - 604X68X0L
    - GJGFY35MV
    dim-1018: []
    dim-31:
    - MBW431N6H
    - 617VQSLDM
    - WL7Z4SLM6
    - 06A4DTSY2
    - VHV66P7GB
    buildersworld:
    - XHHT84SG2
    - B0D4MVADW
    - KXURMGY1F
    dim-28:
    - HFBHVUIJP
    - L998NVCK9
    - 94MZ9CYHW
    - NMYP7WGZC
    - R530G5CFN
    - R665IWYI7
    - 4X9XD6ODL
    - XIMGR35T8
    - B1BV91WBM
    - ZMO6S6A3A
    - ZSTY7BYPW
    - 7FDBNSTP5
    - GOH7E3NAC
    - TDD3LHS0S
    dim-1008: []
    dim-29:
    - G9TZ8ZKS1
    - Z39N3DQ9X
    - MHRXU5BM0
    builder:
    - 64U504OBW
    dim-1:
    - UZO17LS5L
    dim1:
    - 1ZDOLRXOL
    - 7SZXW6JRJ
    dim-1005:
    - XHKEVCGSV
